 DROP TABLE IF EXISTS TGT_EMADEPRODUCTLIST; -- CREATE TARGET TABLE
 CREATE TABLE TGT_EMADEPRODUCTLIST
( PRODUCTID INT NOT NULL,
 PRODUCTNAME VARCHAR(50),
 PRICE MONEY,
 STARTDATE DATE,
 ENDDATE DATE,
 IS_ACTIVE VARCHAR(1) );

 -- INSERT INITIAL DATA INTO TARGET TABLE
 INSERT INTO TGT_EMADEPRODUCTLIST (PRODUCTID, PRODUCTNAME, PRICE, STARTDATE, ENDDATE, IS_ACTIVE)
 VALUES (101, 'TEA', 10.00, '2024-01-01', NULL, 'Y'), (102, 'COFFEE', 15.00, '2024-01-01', NULL, 'Y'),
 (103, 'BISCUITS', 20.00, '2024-01-01', NULL, 'Y');
 
  DROP TABLE IF EXISTS STG_EMADEPRODUCTUPDATEDLIST
 -- CREATE SOURCE TABLE
CREATE TABLE STG_EMADEPRODUCTUPDATEDLIST
( PRODUCTID INT NOT NULL,
PRODUCTNAME VARCHAR(50),
PRICE MONEY );

-- INSERT UPDATED DATA INTO SOURCE TABLE

INSERT INTO STG_EMADEPRODUCTUPDATEDLIST (PRODUCTID, PRODUCTNAME, PRICE)
VALUES (101, 'TEA', 10.00), (102, 'COFFEE', 35.00), (104, 'CHIPS', 22.00);

SELECT * FROM TGT_EMADEPRODUCTLIST SELECT * FROM STG_EMADEPRODUCTUPDATEDLIST

--PERFORMING MERGE OPERATIONS

INSERT INTO TGT_EMADEPRODUCTLIST (PRODUCTID, PRODUCTNAME, PRICE, STARTDATE, ENDDATE, IS_ACTIVE)
SELECT PRODUCTID, PRODUCTNAME, PRICE, STARTDATE, ENDDATE, IS_ACTIVE
FROM (
    MERGE INTO TGT_EMADEPRODUCTLIST AS TARGET
    USING STG_EMADEPRODUCTUPDATEDLIST AS SOURCE
    ON TARGET.PRODUCTID = SOURCE.PRODUCTID AND TARGET.IS_ACTIVE = 'Y'
    WHEN MATCHED THEN
        UPDATE SET
            TARGET.IS_ACTIVE = 'N',
            TARGET.ENDDATE = GETDATE()
    WHEN NOT MATCHED THEN
        INSERT (PRODUCTID, PRODUCTNAME, PRICE, STARTDATE, ENDDATE, IS_ACTIVE)
        VALUES (SOURCE.PRODUCTID, SOURCE.PRODUCTNAME, SOURCE.PRICE, GETDATE(), NULL, 'Y')
    OUTPUT $ACTION,
        SOURCE.PRODUCTID,
        SOURCE.PRODUCTNAME,
        SOURCE.PRICE,
        GETDATE(),
        NULL,
        'Y'
) AS [CHANGES] (ACTION, PRODUCTID, PRODUCTNAME, PRICE, STARTDATE, ENDDATE, IS_ACTIVE)
WHERE ACTION = 'UPDATE';

--ANALYZE SCD OPERATION
SELECT * FROM TGT_EMADEPRODUCTLIST
SELECT * FROM STG_EMADEPRODUCTUPDATEDLIST 